### ISSUE TITLE
URL non funzionante?

### ISSUE THREAD

**Issue by FabioLuporini** [andregri/fantacalcio-voti-live#1]
Ciao,

CI sta che la stringa per le query dei voti debba esser aggiornata per quest anno? La sto provando ma a prescindere dai valori che uso mi ributta sempre su pagina non trovato

**Comment by andregri** [comment]
Ciao grazie per la segnalazione. Sì e molto probabile che qualche codice sia cambiato per la nuova stagione. Provo a correggerlo questa settimana, altrimenti aspetto l'inizio della prossima giornata.

**Comment by FabioLuporini** [comment]
Grazie mille! Tengo un occhio su questa pagina :)

**Comment by andregri** [comment]
L'API dei voti live è diventata un po' più complessa da leggere perché i messaggi sono codificati con protobuf :angry: . Per il momento ho dovuto decodificare i messaggi con le stesse funzioni javascript usate nel sito web. Per questo motivo è necessario installare anche nodejs e la libreria protobufjs

**Comment by FabioLuporini** [comment]
Grazie mille! 

Visto che lasciano l'API pubblica, non capisco perchè non la documentino anche :-)

**Comment by FabioLuporini** [comment]
Mi spiego meglio: io ho scoperto della sua esistenza solo perchè googlando sono arrivato su questo repo !
