### ISSUE TITLE
Domanda

### ISSUE THREAD

**Issue by FabioLuporini** [andregri/fantacalcio-voti-live#4]
Ciao di nuovo e grazie per gli updates recenti!

Domanda: si possono anche accedere i voti delle giornate passate? 

Mi farebbe comodo per sviluppo e debugging

Grazie!

**Comment by FabioLuporini** [comment]
Dimenticavo: se rimango con l'URI predefinita, quindi con `.../live/...`, ritorna una exception 

Ispezionando la response:

```
In [3]: response.json()
Out[3]:
{'ae2b1423-2e05-46c7-92e5-294a75071193': {'expire': None,
  'resources': [],
  'errors': [{'statusCode': 404,
    'statusDescription': 'Not Found',
    'message': None}]}}
```

Scusa se la domanda è stupida, ma questo proprio non è il mio mondo :D

**Comment by andregri** [comment]
Ciao!
### Domanda 1: si può accedere ai voti delle giornate passate?
No, purtroppo l'api di fantagazzetta funziona solamente mentre la giornata è in corso. Io personalmente non ho salvato tutti i dati delle giornate passate a parte una che uso per i test. Puoi eseguire lo script `utils.py`:
```console
$ python3 utils.py
{
    "protoData": [
        {
            "matchId": 13515,
            "stampMatch": 7166,
            "teamIdHome": 6,
            "teamIdAway": 1,
...
```

### Domanda 2: perché l'url `https://api.fantacalcio.it/v1/st/{season_id}/matches/live/{giornata}.dat` non funziona?
Oggi ottieni un errore 404 perché appunto quelli di fantagazzetta "spengono" l'API quando non ci sono giornate in corso. Se vuoi vederla funzionare, dovrai aspettare la prossima giornata...


Adesso questo repo è un po' incasinato, ma potrebbe avere senso metterlo in ordine, visto che lo stai usando.
Se ti serve una mano per scaricare questi dati o altro fammi sapere! 😄

**Comment by FabioLuporini** [comment]
Grazie mille 🙏 

Allora, eseguendo utils.py ricevo questo errore:

```
/fantacalcio-voti-live/decode_livemessage_pb.js:11
var buffer = Uint8Array.from(atob(payload), c => c.charCodeAt(0))
                        ^

ReferenceError: atob is not defined
    at Object.<anonymous> (/fantacalcio-voti-live/decode_livemessage_pb.js:11:25)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Effettivamente `atob` non è definita nel file


E, sì, alla fine mi basta una giornata qualunque per sviluppo/debugging :-) sarebbe perfetto andasse questa

**Comment by andregri** [comment]
Sembra un problema di versione di nodejs che hai installato.
Comunque nell'ultima commit ho sostituito `atob()` con `Buffer.from`, che sembra anche il metodo più consigliato e non dovrebbe dipendere dalla versione.
